### ISSUE TITLE
Remove data-ascii

### ISSUE THREAD

**Issue by chris-martin** [typeclasses/ascii#6]
@frasertweedale (https://github.com/snoyberg/ascii/issues/6#issuecomment-624384806)

> I note you re-export `Data.ASCII` presumably for backwards compat, having moved the old *ascii* package to *data-ascii*. But *data-ascii* is still marked as deprecated, so what is the intention going forward with these modules?

**Comment by chris-martin** [comment]
I don't really have a plan for when to remove the backwards compat modules. I don't have any sense of whether there is anybody who needs them, so I figured I'd delay answering the question until it felt like a problem, to allow more time for anyone who might care to weigh in. I'd also like to be sure we're not throwing out any features that don't have a suitable replacement in the new modules (e.g. you've already brought up case-insensitive comparisons, which iirc the old package supported and mine doesn't yet).

**Comment by frasertweedale** [comment]
Right now there is:

```
    reexported-modules: Data.Ascii
    reexported-modules: Data.Ascii.Blaze
    reexported-modules: Data.Ascii.ByteString
    reexported-modules: Data.Ascii.Word8
```

In a future release, I'd suggest removing the re-exports and the dependency on *data-ascii* and redefine those modules in *this* package with a module-level `DEPRECATED` pragma pointing folks to *data-ascii*:
```
module Data.Ascii {-# DEPRECATED "Data.Ascii is now provided by the 'data-ascii' package." #-} where
<EOF>
```

Of course this will break builds.  Maybe there's a way to use package renaming or something that avoids it and still provides the deprecation warning.  Later still the "stub" modules could be removed.

Or you could just leave it as-is.  Not the end of the world.
